#!/usr/bin/env bash
set -euo pipefail

dotfiles_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
mise_config_dir="$dotfiles_dir/.config/mise"
mise_bin="${HOME:?}/.local/bin/mise"
profile=""
env_list=""
install_system=false

# The manifest path is resolved relative to this script at runtime.
# shellcheck disable=SC1091
source "$dotfiles_dir/.mise-bootstrap.env"
[[ $MISE_VERSION =~ ^[0-9]{4}\.[0-9]{1,2}\.[0-9]+$ ]] || {
  printf 'error: invalid mise version in .mise-bootstrap.env\n' >&2
  exit 1
}
[[ $MISE_SHA256_X64 =~ ^[0-9a-f]{64}$ && $MISE_SHA256_ARM64 =~ ^[0-9a-f]{64}$ ]] || {
  printf 'error: invalid mise checksum in .mise-bootstrap.env\n' >&2
  exit 1
}
readonly MISE_VERSION MISE_SHA256_X64 MISE_SHA256_ARM64

log() {
  printf '==> %s\n' "$*"
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage: ./bootstrap.sh [--profile NAME | --env LIST] [--system]

Options:
  --profile NAME  Select a committed profile from .config/mise/profiles.
  --env LIST      Select a comma-separated list of mise environments.
  --system        Explicitly install declared host packages (may use sudo).
  -h, --help      Show this help.

With no profile option, bootstrap reuses the existing local selection.
EOF
}

while (($#)); do
  case "$1" in
    --profile)
      (($# >= 2)) || die "--profile requires a value"
      profile=$2
      shift 2
      ;;
    --env)
      (($# >= 2)) || die "--env requires a value"
      env_list=$2
      shift 2
      ;;
    --system)
      install_system=true
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

[[ -z $profile || -z $env_list ]] || die "--profile and --env are mutually exclusive"
[[ $(uname -s) == Linux ]] || die "only Linux hosts are supported"

case "$(uname -m)" in
  x86_64 | amd64)
    mise_arch=x64
    mise_sha256=$MISE_SHA256_X64
    ;;
  aarch64 | arm64)
    mise_arch=arm64
    mise_sha256=$MISE_SHA256_ARM64
    ;;
  *)
    die "unsupported architecture: $(uname -m)"
    ;;
esac

install_mise() {
  local installed_version=""
  local tmp_dir=""
  local download=""
  local url=""

  if [[ -x $mise_bin ]]; then
    installed_version="$(MISE_NO_CONFIG=1 "$mise_bin" --version 2>/dev/null | awk '{print $1}')"
  fi
  if [[ $installed_version == "$MISE_VERSION" ]]; then
    log "mise $MISE_VERSION is already installed"
    return
  fi

  command -v curl >/dev/null || die "curl is required to install mise"
  command -v sha256sum >/dev/null || die "sha256sum is required to verify mise"

  tmp_dir="$(mktemp -d -t dotfiles-mise.XXXXXXXXXX)"
  [[ -n $tmp_dir && -d $tmp_dir ]] || die "failed to create a temporary directory"
  trap '[[ -n ${tmp_dir:-} && -d ${tmp_dir:-} ]] && rm -r -- "$tmp_dir"' RETURN
  download="$tmp_dir/mise"
  url="https://github.com/jdx/mise/releases/download/v${MISE_VERSION}/mise-v${MISE_VERSION}-linux-${mise_arch}"

  log "downloading mise $MISE_VERSION for linux-$mise_arch"
  curl --fail --location --proto '=https' --tlsv1.2 --output "$download" "$url"
  printf '%s  %s\n' "$mise_sha256" "$download" | sha256sum --check --status - ||
    die "mise checksum verification failed"

  mkdir -p -- "$(dirname "$mise_bin")"
  install -m 0755 -- "$download" "$mise_bin"
  [[ "$(MISE_NO_CONFIG=1 "$mise_bin" --version | awk '{print $1}')" == "$MISE_VERSION" ]] ||
    die "installed mise version does not match $MISE_VERSION"
  log "installed verified mise $MISE_VERSION at $mise_bin"
}

is_generated_selection() {
  [[ -f $1 ]] && IFS= read -r first_line <"$1" && [[ $first_line == "# Generated by bootstrap.sh" ]]
}

prepare_selection_target() {
  local selection=$1

  if [[ -L $selection ]]; then
    rm -- "$selection"
  elif [[ -e $selection ]]; then
    is_generated_selection "$selection" ||
      die "refusing to replace unmanaged profile selection: $selection"
    rm -- "$selection"
  fi
}

select_profile() {
  local selection="$mise_config_dir/miserc.toml"
  local profile_file=""
  local profile_target=""

  if [[ -n $profile ]]; then
    [[ $profile =~ ^[a-z0-9][a-z0-9-]*$ ]] || die "invalid profile name: $profile"
    profile_file="$mise_config_dir/profiles/$profile.miserc.toml"
    [[ -f $profile_file ]] || die "unknown profile: $profile"
    profile_target="profiles/$profile.miserc.toml"
    if [[ -L $selection && $(readlink -- "$selection") == "$profile_target" ]]; then
      log "profile $profile is already selected"
      return
    fi
    prepare_selection_target "$selection"
    ln -s -- "$profile_target" "$selection"
    log "selected profile $profile"
    return
  fi

  if [[ -n $env_list ]]; then
    local -a environments=()
    local environment=""
    local saw_personal=false
    local saw_work=false
    local tmp_selection=""

    IFS=',' read -r -a environments <<<"$env_list"
    ((${#environments[@]} > 0)) || die "--env must not be empty"
    for environment in "${environments[@]}"; do
      [[ $environment =~ ^[a-z0-9][a-z0-9-]*$ ]] || die "invalid environment: $environment"
      [[ -f "$mise_config_dir/config.$environment.toml" ]] ||
        die "unknown environment: $environment"
      [[ $environment == personal ]] && saw_personal=true
      [[ $environment == work ]] && saw_work=true
    done
    [[ $saw_personal == false || $saw_work == false ]] ||
      die "personal and work environments are mutually exclusive"

    prepare_selection_target "$selection"
    tmp_selection="$(mktemp "$mise_config_dir/.miserc.toml.XXXXXXXXXX")"
    {
      printf '# Generated by bootstrap.sh\n'
      printf 'env = ['
      local separator=""
      for environment in "${environments[@]}"; do
        printf '%s"%s"' "$separator" "$environment"
        separator=', '
      done
      printf ']\n'
    } >"$tmp_selection"
    mv -- "$tmp_selection" "$selection"
    log "selected environments: ${env_list//,/, }"
    return
  fi

  [[ -e $selection || -L $selection ]] || {
    printf 'Available profiles:\n' >&2
    find "$mise_config_dir/profiles" -maxdepth 1 -name '*.miserc.toml' -printf '  %f\n' |
      sed 's/\.miserc\.toml$//' >&2
    die "select a profile with --profile or environments with --env"
  }
  log "reusing the existing mise environment selection"
}

install_mise
"$dotfiles_dir/scripts/link_shell_dotfiles.sh"
select_profile

export MISE_CONFIG_DIR="$mise_config_dir"
export MISE_TRUSTED_CONFIG_PATHS="$dotfiles_dir"

if [[ $install_system == true ]]; then
  if [[ -f /usr/share/qubes/marker-vm || $profile == qubes-* ]]; then
    die "system packages belong in the Qubes TemplateVM; refusing --system in an AppVM profile"
  fi
  log "installing explicitly requested host packages"
  "$mise_bin" bootstrap packages apply --yes
fi

log "applying pinned shell and tmux plugin repositories"
"$mise_bin" bootstrap repos apply --yes

log "installing tools from committed lockfiles"
"$mise_bin" install --locked

log "synchronizing host-specific shell integrations"
PATH="$(dirname "$mise_bin"):$PATH" \
  "$mise_bin" exec -- "$dotfiles_dir/scripts/sync_shell_integrations.sh"

log "bootstrap complete"
