[bootstrap.packages]
"apt:bash-completion" = "latest"
"apt:ca-certificates" = "latest"
"apt:curl" = "latest"
"apt:git" = "latest"
"apt:htop" = "latest"
"apt:rsync" = "latest"
"apt:tmux" = "latest"
"apt:zsh" = "latest"
